name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Xcode Command Line Tools
        run: xcode-select --install
      
      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.9'
      
      - name: Build package
        run: swift build -v
      
      - name: Run tests
        run: swift test -v
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            SNKit ${{ github.ref_name }} 릴리스
            
            ### 주요 변경사항
            - 이미지 캐싱 라이브러리 업데이트
            - 안정성 및 성능 개선